version: '3'
services:
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ./:/var/www
  nginx:
    build:
      context: ./nginx
    restart: always
    volumes:
      - ./:/var/www
    ports:
      - "80:80"
    depends_on:
      - php-fpm
   
  maria_db:
   image: mariadb
   environment:
     MYSQL_ROOT_PASSWORD: secret
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
        - maria_db:db
    ports:
        - "8080:80"
    environment:
        MYSQL_USERNAME: root
        MYSQL_ROOT_PASSWORD: secret
